#!/bin/bash

PROJECT_ROOT="$(cd "$(dirname "$0")"/../../../ && pwd)"

osascript <<EOF
tell application "Terminal"
    activate
    do script "cd \"$PROJECT_ROOT\" && chmod +x install.command && ./install.command"
end tell
EOF
